default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sd_development

test:
  <<: *default
  database: sd_test

production:
  <<: *default
  url: <%= ENV['database_url'] %>
