require 'rspec/expectations'
require 'graphql/guard/testing'

# Example use:
# expect(resolver_for(my_type).with(obj, args, ctx)).to authorize_field('my_field')
#
RSpec::Matchers.define :authorize_field do |field|
  # Accepts an array of [:type, :obj, :args, :ctx], as can be generated by #resolver_for(...).with(obj, args, ctx)
  match do |type_resolver|
    @type, @obj, @args, @ctx = type_resolver
    @authorized = @type.field_with_guard(field).guard(@obj, @args, @ctx)
    expect(@authorized).to be true
  end

  failure_message do |_|
    "expected `#{field}` to be authorized, with (`#{@obj}`, `#{@args}`, `#{@ctx}`)"
  end

  description do
    "authorize field `#{field}`"
  end
end
